// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelConnect() {
  return window['go']['main']['App']['CancelConnect']();
}

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function ConnectWithAuth(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ConnectWithAuth'](arg1, arg2, arg3, arg4);
}

export function ConnectWithKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectWithKey'](arg1, arg2, arg3);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetDefaultSSHKeys() {
  return window['go']['main']['App']['GetDefaultSSHKeys']();
}

export function GetDeviceInfo() {
  return window['go']['main']['App']['GetDeviceInfo']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function RunCommand(arg1) {
  return window['go']['main']['App']['RunCommand'](arg1);
}

export function RunCommandWithOutput(arg1) {
  return window['go']['main']['App']['RunCommandWithOutput'](arg1);
}

export function SelectKeyFile() {
  return window['go']['main']['App']['SelectKeyFile']();
}
