// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelConnect():Promise<void>;

export function Connect(arg1:string,arg2:string):Promise<main.ConnectionResult>;

export function ConnectWithAuth(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.ConnectionResult>;

export function ConnectWithKey(arg1:string,arg2:string,arg3:string):Promise<main.ConnectionResult>;

export function Disconnect():Promise<void>;

export function GetDefaultSSHKeys():Promise<Array<main.SSHKey>>;

export function GetDeviceInfo():Promise<Record<string, string>>;

export function IsConnected():Promise<boolean>;

export function RunCommand(arg1:string):Promise<string>;

export function RunCommandWithOutput(arg1:string):Promise<void>;

export function SelectKeyFile():Promise<string>;
