name: Flatpak Release

on:
  push:

jobs:
  build-x86_64:
    name: Build Flatpak (x86_64)
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-49
      options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: reManager-x86_64.flatpak
          manifest-path: flatpak/io.scottlabs.reManager.yml
          arch: x86_64
          cache-key: flatpak-builder-x86_64-${{ github.sha }}

  build-aarch64:
    name: Build Flatpak (aarch64)
    runs-on: ubuntu-24.04-arm
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-49
      options: --privileged

    steps:
      - uses: actions/checkout@v4

      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: reManager-aarch64.flatpak
          manifest-path: flatpak/io.scottlabs.reManager.yml
          arch: aarch64
          cache-key: flatpak-builder-aarch64-${{ github.sha }}
